create table public.ai_generation_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_at timestamptz not null default now(),
  rate_bucket timestamptz not null,
  constraint ai_generation_usage_user_bucket_key unique (user_id, rate_bucket)
);

create index ai_generation_usage_user_requested_at_idx
on public.ai_generation_usage (user_id, requested_at desc);

alter table public.ai_generation_usage enable row level security;

revoke all on table public.ai_generation_usage from anon;
grant select, insert on table public.ai_generation_usage to authenticated;
grant usage, select on sequence public.ai_generation_usage_id_seq to authenticated;

create policy "Team members can read their own AI usage"
on public.ai_generation_usage for select to authenticated
using (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.team_members
    where team_members.email = lower((select auth.jwt())->>'email')
      and team_members.active
  )
);

create policy "Team members can record their own AI usage"
on public.ai_generation_usage for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.team_members
    where team_members.email = lower((select auth.jwt())->>'email')
      and team_members.active
  )
);
